from googlesearch import search
from pytube import YouTube


#NEed to increase audio quality and convert to audio only file

#Initializes variables and gets user input
song = input()
str.capitalize(song)
Quarry = song + ' song'
print(Quarry)
songList = []
songListCorrect = []

for j in search(Quarry, tld="co.in", num=10, stop=10, pause=2):
    if 'youtube' in j:
        songList.append(j)#searches for user input

for i in songList:
    yt = YouTube(i)
    desc = yt.description
    if 'by YouTube' in desc:
        songListCorrect.append(i)#finds video that was auto generated by youtube

link = songListCorrect[0]
yt = YouTube(link)
#downloads video
stream = yt.streams.first()

stream.download()

print('All done')
